### PR TITLE
Updated rsocket version

### PR DESCRIPTION
**Pull request by segabriel**

### CODE REVIEW

**Comment by segabriel** [comment]
There is a bug with onClose event in this rsocket version

**Comment by artem-v** [comment]
@segabriel 
> There is a bug with onClose event in this rsocket version

How do u know that ? 

I saw in travis logs only this fail: 
```
E 0731-0844:05,831 i.s.s.r.Routers Create router type: class io.scalecube.services.routings.sut.DummyRouter failed: java.lang.NullPointerException [main]
```

**Comment by segabriel** [comment]
@artem-v 
Yeah a test generates it when check creating router with Dummy

**Comment by segabriel** [comment]
There is a bug with onClose event in this rsocket version

**Pull request closed without merging**
