### PR TITLE
Added protostuff support for codec

### PR DESCRIPTION
**Pull request by segabriel**

### CODE REVIEW

**Review by artem-v — CHANGES_REQUESTED** [review]
Let's add body protostuff codec also

**Comment by ronenhamias** [comment]
please create example that shows this codecs works and how it works in service layer with tests

**Review by ronenhamias — CHANGES_REQUESTED** [review]
need examples + tests

**Comment by ronenhamias** [comment]
update readme file (maven section)

**Comment by segabriel** [comment]
@ronenhamias so I added tests to check the both current protocols

**Review by artem-v — CHANGES_REQUESTED** [review]
Plz update scalecube benchmarks to `1.1.13`

**Review by artem-v — APPROVED** [review]

**Pull request merged**
